// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hundqibqzckfpetpgkfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1bmRxaWJxemNrZnBldHBna2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMTEwOTksImV4cCI6MjA3Mzg4NzA5OX0.4lr1XJ153VnPm-nbU48HqGx8ngDReG3o8f40ouO282c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});